steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: 'asia-south1-docker.pkg.dev/edgepulse-prod-509316/edgepulse-repo/edgepulse:latest'

images:
  - '$_IMAGE'
